stages:
- deploy

deploy-api:
  stage: deploy
  tags:
    - bare
  variables:
    IMAGE_DEPLOY: $CI_REGISTRY/saas2/core:latest
    IMAGE_HAPROXY_CLI: "$CI_REGISTRY/saas2/haproxy-letsencrypt:latest"
    HAPROXY_BACKEND: "http://192.168.1.8:6300"
    APP_HOST: "formula1.alexa.nextagilesoft.com"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull ${IMAGE_HAPROXY_CLI}
    - docker pull ${IMAGE_DEPLOY}
    - docker run -v `pwd`/app.yml:/app.yml --rm ${IMAGE_DEPLOY} deploy --env=prod --config=/app.yml
    - docker run --rm ${IMAGE_HAPROXY_CLI} certificates add --backend-url=${HAPROXY_BACKEND} --certificate=${APP_HOST}
